language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: "test"
      script: npm test
    - stage: "deploy"
      script: npm run build:clean
      deploy:
        provider: s3
        bucket: tests3deploy
        region: eu-north-1
        local_dir: ./dist
        verbose: true
        edge: true # opt in to dpl v2
        on:
          branch: ["testing"]